const HOME_SCREEN = 'HOME_SCREEN';
const NEW_DETAILS_SCREEN = 'NEW_DETAILS_SCREEN';
const SPLASH_SCREEN = 'SPLASH_SCREEN';
const LOGIN_SCREEN = 'LOGIN_SCREEN';

export {
    HOME_SCREEN, NEW_DETAILS_SCREEN, SPLASH_SCREEN, LOGIN_SCREEN
}